# This workflow will build a golang project for multiple platforms
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, arm]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build DANP-MCP-CLIENT
      run: |
        if [ "${{ matrix.platform }}" = "arm" ]; then
          GOOS=${{ matrix.platform }} GOARCH=arm64 go build -ldflags "-s -w -X \"main.BuildVersion=${{ github.sha }}\" -X \"main.BuildDate=$(date -u '+%Y-%m-%d %H:%M:%S')\"" -o bin/DANP-MCP-CLIENT-${{ matrix.platform }} ./cmd/DANP-MCP-CLIENT
        else
          GOOS=${{ matrix.platform }} GOARCH=amd64 go build -ldflags "-s -w -X \"main.BuildVersion=${{ github.sha }}\" -X \"main.BuildDate=$(date -u '+%Y-%m-%d %H:%M:%S')\"" -o bin/DANP-MCP-CLIENT-${{ matrix.platform }}${{ matrix.platform == 'windows' && '.exe' || '' }} ./cmd/DANP-MCP-CLIENT
        fi

    - name: Build DANP-MCP-SERVER
      run: |
        if [ "${{ matrix.platform }}" = "arm" ]; then
          GOOS=${{ matrix.platform }} GOARCH=arm64 go build -ldflags "-s -w -X \"main.BuildVersion=${{ github.sha }}\" -X \"main.BuildDate=$(date -u '+%Y-%m-%d %H:%M:%S')\"" -o bin/DANP-MCP-SERVER-${{ matrix.platform }} ./cmd/DANP-MCP-SERVER
        else
          GOOS=${{ matrix.platform }} GOARCH=amd64 go build -ldflags "-s -w -X \"main.BuildVersion=${{ github.sha }}\" -X \"main.BuildDate=$(date -u '+%Y-%m-%d %H:%M:%S')\"" -o bin/DANP-MCP-SERVER-${{ matrix.platform }}${{ matrix.platform == 'windows' && '.exe' || '' }} ./cmd/DANP-MCP-SERVER
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DANP-Engine-${{ matrix.platform }}
        path: |
          bin/DANP-MCP-CLIENT-${{ matrix.platform }}*
          bin/DANP-MCP-SERVER-${{ matrix.platform }}*
          bin/*.exe
